export const CODE_EXPIRATION_MINUTES = 10;
export const MAX_PIN_ATTEMPTS = 5;
export const PIN_LOCK_DURATION_MINUTES = 15;

export const VERIFY_PIN_RATE_LIMIT_MAX = 5;
export const VERIFY_PIN_RATE_LIMIT_WINDOW_MS = PIN_LOCK_DURATION_MINUTES * 60 * 1000;
